spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/easybank_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-plateform: org.hibernate.dialect.PostgreSQLDialect
